ROOKDICT
 Q
 ;
EGGPROP(EGG,KEY)
 Q $G(^ROOK("DD",$$CURRENTNEST^ROOK,EGG,KEY))
 ;
EMBRPROP(EGG,EMBRYO,KEY)
 Q $G(^ROOK("DD",$$CURRENTNEST^ROOK,EGG,"EMBRYOS",EMBRYO,KEY))
 ;
EGGHOOKS(EGG,HOOK,RESULT)
 I $D(^ROOK("DD",$$CURRENTNEST^ROOK,EGG,"HOOKS")) D
 . M RESULT=^ROOK("DD",$$CURRENTNEST^ROOK,EGG,"HOOKS")
 Q $G(^ROOK("DD",$$CURRENTNEST^ROOK,EGG,"HOOKCOUNT"))
 ;
TYPE(EGG,EMBRYO)
 Q $$EMBRPROP(EGG,EMBRYO,"TYPE")
 ;
IXFORM(EGG,EMBRYO)
 Q $$EMBRPROP(EGG,EMBRYO,"INPUTXFORM")
 ;
OXFORM(EGG,EMBRYO)
 Q $$EMBRPROP(EGG,EMBRYO,"OUTPUTXFORM")
 ;
PATTERN(EGG,EMBRYO)
 Q $$EMBRPROP(EGG,EMBRYO,"PATTERN")
 ;
PRIMARY(EGG,EMBRYO)
 Q $$EMBRPROP(EGG,EMBRYO,"PRIMARY")
 ;
UNIQUE(EGG,EMBRYO)
 Q $$EMBRPROP(EGG,EMBRYO,"UNIQUE")
 ;
REQUIRED(EGG,EMBRYO)
 Q $$EMBRPROP(EGG,EMBRYO,"REQUIRED")
 ;
MAXLENGTH(EGG,EMBRYO)
 Q $$EMBRPROP(EGG,EMBRYO,"MAXLENGTH")
 ;
INDEXED(EGG,EMBRYO)
 N RET S RET=1
 I $$TYPE(EGG,EMBRYO)="STRING" D
 . S RET=($$MAXLENGTH(EGG,EMBRYO)<81)
 Q RET
 ;