ROOKDA
 Q
 ;
REORDER(DAIN,DAOUT,EGG,EMBRYO,RESULT)
 N TMP,ENUM,TIDX,CNAM,MAP,OIDX,TIMER,QTIME
 S ENUM="",TIDX=1,OIDX=1
 S TIMER=$$BTIME^ROOK
 ; 
 ; REORDER FIRST BY EMBRYO VALUE THEN BY TIDX (SEQUENTIAL) 
 ;
 F  S ENUM=$O(DAIN(EGG,ENUM)) Q:ENUM=""  D
 . S TMP(DAIN(EGG,ENUM,EMBRYO),TIDX)=ENUM
 . S TIDX=$I(TIDX)
 ;
 ; BUILD THE MAPPINGS
 ; 
 S (CNAM,TIDX)=""
 F  S CNAM=$O(TMP(CNAM)) Q:CNAM=""  D
 . S TIDX=""
 . F  S TIDX=$O(TMP(CNAM,TIDX)) Q:TIDX=""  D
 . . S ENUM=TMP(CNAM,TIDX)
 . . S MAP(OIDX)=ENUM
 . . S OIDX=$I(OIDX)
 ;
 ; MERGE INTO NEW ORDER 
 ;
 S OIDX=""
 F  S OIDX=$O(MAP(OIDX)) Q:OIDX=""  D
 . M DAOUT(EGG,OIDX)=DAIN(EGG,MAP(OIDX))
 ;
 ; CALCULATE QUERY TIME AND RETURN
 ;
 S QTIME=$$ETIME^ROOK(TIMER)
 D SUCCESS^ROOK(.RESULT,0,QTIME,0,.DAOUT)
 Q RKRESULT
 ;