ROOKVALI
 Q
 ;
PATTERN(VALUE,PATTERN)
 Q VALUE?@PATTERN
 ;
DATATYPE(TYPE)
 N VALID S VALID=1
 G:TYPE="STRING" DTEND
 G:TYPE="NUMBER" DTEND
 G:TYPE="HOROLOG" DTEND
 G:TYPE="BOOLEAN" DTEND
 S VALID=0
DTEND
 Q VALID
 ;
BOOLEAN(VALUE)
 N VALID S VALID=1
 G:VALUE=1 BOOLEND
 G:VALUE=0 BOOLEND
 S VALID=0
BOOLEND
 Q VALID
 ;
NUMBER(VALUE)
 N VALID,CHAR S VALID=1,CHAR=""
 N GOODCHAR S GOODCHAR="0123456789.-"
 I $L(VALUE,".")>2 S VALID=0
 I $L(VALUE,"-")>2 S VALID=0
 I $L(VALUE,"-")=2 D
 . I $E(VALUE,1,1)'="-" S VALID=0
 . I $L(VALUE)=1 S VALID=0
 G:VALID=0 NUMEND
 N LENGTH S LENGTH=$L(VALUE)
 F I=1:1:LENGTH  D
 . S CHAR=$E(VALUE,I,I)
 . I '(GOODCHAR[CHAR) S VALID=0
NUMEND
 Q VALID
 ;
STRING(VALUE)
 N VALID S VALID=1
 I $$NUMBER(VALUE) S VALID=0
 I $$BOOLEAN(VALUE) S VALID=0
 I $$HORO(VALUE) S VALID=0
STREND
 Q VALID
 ;
HORO(VALUE)
 N VALID S VALID=1
 I $L(VALUE,",")'=2 S VALID=0
 I $L(VALUE,",")=2 D
 . I '$$NUMBER($P(VALUE,",",1)) S VALID=0
 . I '$$NUMBER($P(VALUE,",",2)) S VALID=0
 Q VALID
 ;
BYTYPE(DATATYPE,VALUE)
 N VALID S VALID=1
 I DATATYPE="STRING" S VALID=$$STRING(VALUE)
 I DATATYPE="NUMBER" S VALID=$$NUMBER(VALUE)
 I DATATYPE="HOROLOG" S VALID=$$HORO(VALUE)
 I DATATYPE="BOOLEAN" S VALID=$$BOOLEAN(VALUE)
 Q VALID
 ; 